version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
     - "8001:8001"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - TZ=America/Guayaquil
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rental
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      
  db:
    image: 'postgres:13.1-alpine'
    ports:
     - "8002:5432"
    container_name: db
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rental