spring:
  application:
    name: rentaVehiculo
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  sql:
    init:
      mode: ALWAYS
      continue-on-error: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
server:
  port: 8001