spring:
  application:
    name: rentaVehiculo
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: ALWAYS
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://localhost:5432/rental
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 
server:
  port: 8001